# define the location of the eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
server:
  port: 8903
spring:
  thymeleaf:
    cache: false
  application:
    name: other-consumer
#---
#spring:
## when the cloud profile is activated then we need to tell eurek our route
#  profiles: cloud
#eureka:
#  instance:
#    hostname: ${vcap.application.uris[0]}
#    nonSecurePort: 80